/*
 * InstructionsPanel.java
 *
 * Created on September 15, 2008, 12:55 PM
 */

package gui;

import application.IAppContext;

/**
 *
 * @author  kamlesh paunikar
 */
public class InstructionsPanel extends javax.swing.JPanel {

    /** Creates new form InstructionsPanel */
    public InstructionsPanel(IAppContext appContext) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionScrollPane = new javax.swing.JScrollPane();
        instructionTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        instructionTextArea.setColumns(20);
        instructionTextArea.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        instructionTextArea.setRows(5);
        instructionTextArea.setMargin(new java.awt.Insets(5, 5, 2, 2));
        instructionScrollPane.setViewportView(instructionTextArea);

        add(instructionScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public String getInstructions()
    {
        return instructionTextArea.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane instructionScrollPane;
    private javax.swing.JTextArea instructionTextArea;
    // End of variables declaration//GEN-END:variables

}
